### ISSUE TITLE
Streamlit web app is down

### ISSUE THREAD

**Issue by jhrcook** [AlexAndorra/pollsposition_website#2]
When I try to access the website, the Streamlit app is not working. The error message is

```
ValueError: failed to validate Title(id='48436', ...).text: expected a value of type str, got None of type NoneType
```

It looks like there is an error in `gp-popularity-app.py` where you are accidentally passing `None` instead of a string.

**Comment by AlexAndorra** [comment]
Mmmh indeed, that's weird because I didn't modify anything to the version that was still running successfully a few days ago 😅 
It may be due to an update in Bokeh 🤔 I'll look into it when I get some time.
Thanks for raising the issue @jhrcook !

**Comment by AlexAndorra** [comment]
@jhrcook [the app](https://share.streamlit.io/alexandorra/pollsposition_website/main/gp-popularity-app.py) is back online 🥳 
It was indeed a version conflict -- I think I solved this now 😉
